"""add direction check constraint

Revision ID: 9e74d5b851a1
Revises: e5a19e966fdb
Create Date: 2025-10-15 11:29:01.172240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e74d5b851a1'
down_revision: Union[str, Sequence[str], None] = 'e5a19e966fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "check_direction_valid",
        "probes",
        "direction IN ('NORTH', 'SOUTH', 'EAST', 'WEST')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_direction_valid", "probes", type_="check")
    # ### end Alembic commands ###
